# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 146f32197ee86b68b32b24e9b44387ae59b1e16550c6cb80bb0334d6e619c0365b7d25accd0e44c1b9502466554058e672ccdfaff55f8873d659d538efc51a99

test:
  secret_key_base: aaa1073cdfa7d31fafa82c1b7eac253f569d5b04432fdf6755d84af372164de27854bfab2696303728e2421dd63635c86ecafdfecb9edb893cac31575fc55147

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
